### ISSUE TITLE
第一版性能结构问题

### ISSUE THREAD

**Issue by flaght** [mlgoogle/wiki#2]

**Comment by Lockeysama** [comment]
## 第一版待优化修改项

- Socket数据抽象化
- UI通用部分抽象化
- Socket通信数据加密压缩
- Realm数据存储管理类接口模板化
- 支付宝支付
- 迁移Swift3、XCode8问题
- XCGLogged在XCode8下无法正常显示（XCode8问题），替换其他库
- 企业证书推送证书替换
- 公共方法抽取（颜色、字体等）
